create or replace dynamic table DT_DAILY_CITY_KPI(
	FULL_DATE,
	CUSTOMER_CITY,
	RESTAURANT_CITY,
	TOTAL_ORDERS,
	GMV,
	DELIVERED_ORDERS,
	CANCELLED_ORDERS,
	AVG_RATING,
	AVG_SENTIMENT_SCORE,
	AVG_SLA_BREACH_RATE
) target_lag = '1 minute' refresh_mode = AUTO initialize = ON_CREATE warehouse = WH_ZOMATO
 as
SELECT
  FULL_DATE,
  CUSTOMER_CITY,
  RESTAURANT_CITY,
  COUNT(*)                          AS TOTAL_ORDERS,
  SUM(TOTAL_AMOUNT)                 AS GMV,
  SUM(IS_DELIVERED)                 AS DELIVERED_ORDERS,
  SUM(IS_CANCELLED)                 AS CANCELLED_ORDERS,
  ROUND(AVG(RATING), 2)             AS AVG_RATING,
  ROUND(AVG(SENTIMENT_SCORE), 2)    AS AVG_SENTIMENT_SCORE,
  ROUND(AVG(SLA_BREACH_FLAG), 4)    AS AVG_SLA_BREACH_RATE
FROM V_ORDER_ENRICHED
GROUP BY
  FULL_DATE,
  CUSTOMER_CITY,
  RESTAURANT_CITY;
