CREATE OR REPLACE STAGE "ZOMATO_DWH"."RAW"."ZOMATO_EXT_STAGE"
  URL = 'azure://snowflake2azuredemo1.blob.core.windows.net/zomato-landing/'
  STORAGE_INTEGRATION = AZURE_BLOB_INT
  FILE_FORMAT = (BINARY_FORMAT = 'HEX', COMPRESSION = 'AUTO', DATE_FORMAT = 'AUTO', EMPTY_FIELD_AS_NULL = TRUE, ENCODING = 'UTF8', ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\\', FIELD_DELIMITER = ',', FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE', MULTI_LINE = TRUE, NULL_IF = ('\\N'), PARSE_HEADER = FALSE, RECORD_DELIMITER = '\n', REPLACE_INVALID_CHARACTERS = FALSE, SKIP_BLANK_LINES = FALSE, SKIP_BYTE_ORDER_MARK = TRUE, SKIP_HEADER = 0, TIMESTAMP_FORMAT = 'AUTO', TIME_FORMAT = 'AUTO', TRIM_SPACE = FALSE, TYPE = 'CSV', VALIDATE_UTF8 = TRUE)
  COPY_OPTIONS = (ENFORCE_LENGTH = TRUE, FORCE = FALSE, ON_ERROR = 'ABORT_STATEMENT', PURGE = FALSE, RETURN_FAILED_ONLY = FALSE, TRUNCATECOLUMNS = FALSE)
  DIRECTORY = (AUTO_REFRESH = FALSE, ENABLE = FALSE)
  PRIVATELINK = (USE_PRIVATELINK_ENDPOINT = FALSE);

-- Generated at: 2025-11-15 17:30:27 UTC
-- Source SQL: DESC STAGE "ZOMATO_DWH"."RAW"."ZOMATO_EXT_STAGE"
