-- Snapshot for stage ZOMATO_DWH.RAW.ZOMATO_EXT_STAGE (DESCRIBE STAGE)
-- Generated at: 2025-11-15 16:53:31 UTC
-- Source SQL: DESC STAGE ZOMATO_DWH.RAW.ZOMATO_EXT_STAGE

-- parent_property | property | property_type | property_value | property_default
-- STAGE_FILE_FORMAT | TYPE | String | CSV | CSV
-- STAGE_FILE_FORMAT | RECORD_DELIMITER | String | \n | \n
-- STAGE_FILE_FORMAT | FIELD_DELIMITER | String | , | ,
-- STAGE_FILE_FORMAT | FILE_EXTENSION | String |  | 
-- STAGE_FILE_FORMAT | SKIP_HEADER | Integer | 0 | 0
-- STAGE_FILE_FORMAT | PARSE_HEADER | Boolean | false | false
-- STAGE_FILE_FORMAT | DATE_FORMAT | String | AUTO | AUTO
-- STAGE_FILE_FORMAT | TIME_FORMAT | String | AUTO | AUTO
-- STAGE_FILE_FORMAT | TIMESTAMP_FORMAT | String | AUTO | AUTO
-- STAGE_FILE_FORMAT | BINARY_FORMAT | String | HEX | HEX
-- STAGE_FILE_FORMAT | ESCAPE | String | NONE | NONE
-- STAGE_FILE_FORMAT | ESCAPE_UNENCLOSED_FIELD | String | \\ | \\
-- STAGE_FILE_FORMAT | TRIM_SPACE | Boolean | false | false
-- STAGE_FILE_FORMAT | FIELD_OPTIONALLY_ENCLOSED_BY | String | NONE | NONE
-- STAGE_FILE_FORMAT | NULL_IF | List | [\\N] | [\\N]
-- STAGE_FILE_FORMAT | COMPRESSION | String | AUTO | AUTO
-- STAGE_FILE_FORMAT | ERROR_ON_COLUMN_COUNT_MISMATCH | Boolean | true | true
-- STAGE_FILE_FORMAT | VALIDATE_UTF8 | Boolean | true | true
-- STAGE_FILE_FORMAT | SKIP_BLANK_LINES | Boolean | false | false
-- STAGE_FILE_FORMAT | REPLACE_INVALID_CHARACTERS | Boolean | false | false
-- STAGE_FILE_FORMAT | EMPTY_FIELD_AS_NULL | Boolean | true | true
-- STAGE_FILE_FORMAT | SKIP_BYTE_ORDER_MARK | Boolean | true | true
-- STAGE_FILE_FORMAT | ENCODING | String | UTF8 | UTF8
-- STAGE_FILE_FORMAT | MULTI_LINE | Boolean | true | true
-- STAGE_COPY_OPTIONS | ON_ERROR | String | ABORT_STATEMENT | ABORT_STATEMENT
-- STAGE_COPY_OPTIONS | SIZE_LIMIT | Long |  | 
-- STAGE_COPY_OPTIONS | PURGE | Boolean | false | false
-- STAGE_COPY_OPTIONS | RETURN_FAILED_ONLY | Boolean | false | false
-- STAGE_COPY_OPTIONS | ENFORCE_LENGTH | Boolean | true | true
-- STAGE_COPY_OPTIONS | TRUNCATECOLUMNS | Boolean | false | false
-- STAGE_COPY_OPTIONS | FORCE | Boolean | false | false
-- STAGE_LOCATION | URL | String | ["azure://snowflake2azuredemo1.blob.core.windows.net/zomato-landing/"] | 
-- STAGE_INTEGRATION | STORAGE_INTEGRATION | String | AZURE_BLOB_INT | 
-- DIRECTORY | ENABLE | Boolean | false | false
-- DIRECTORY | AUTO_REFRESH | Boolean | false | false
-- PRIVATELINK | USE_PRIVATELINK_ENDPOINT | Boolean | false | false
