-- Snapshot for API INTEGRATION GIT_DDL_API_INTEGRATION (DESCRIBE API INTEGRATION)
-- Generated at: 2025-11-15 15:43:25 UTC
-- Source SQL: DESC API INTEGRATION GIT_DDL_API_INTEGRATION

-- property | property_type | property_value | property_default
-- ENABLED | Boolean | true | false
-- USE_PRIVATELINK_ENDPOINT | Boolean | false | false
-- API_PROVIDER | String | GIT_HTTPS_API | 
-- API_ALLOWED_PREFIXES | List | https://github.com/agarwal194 | []
-- API_BLOCKED_PREFIXES | List |  | []
-- TLS_TRUSTED_CERTIFICATES | List | [] | []
-- COMMENT | String |  | 
