create or replace view V_AGENT_EFFICIENCY_KPI(
	AGENT_ID,
	AGENT_NAME,
	AGENT_CITY,
	ORDERS_DELIVERED,
	AVG_DISTANCE_PER_ORDER,
	AVG_DELIVERY_TIME_MIN,
	SLA_BREACH_RATE,
	DAYS_WORKED,
	AVG_ORDERS_PER_DAY
) as
SELECT
  da.AGENT_ID,
  da.AGENT_NAME,
  da.CITY AS AGENT_CITY,
  COUNT(DISTINCT d.ORDER_ID)                        AS ORDERS_DELIVERED,
  AVG(d.DISTANCE_KM)                                AS AVG_DISTANCE_PER_ORDER,
  AVG(d.ACTUAL_TIME_MIN)                            AS AVG_DELIVERY_TIME_MIN,
  AVG(d.SLA_BREACH_FLAG)                            AS SLA_BREACH_RATE,
  COUNT(DISTINCT DATE_TRUNC('day', d.PICKUP_TIME))  AS DAYS_WORKED,
  CASE WHEN COUNT(DISTINCT DATE_TRUNC('day', d.PICKUP_TIME)) > 0
       THEN COUNT(DISTINCT d.ORDER_ID) / COUNT(DISTINCT DATE_TRUNC('day', d.PICKUP_TIME))
       ELSE NULL
  END                                               AS AVG_ORDERS_PER_DAY
FROM INT.FCT_DELIVERY d
JOIN INT.DIM_DELIVERY_AGENT da
  ON d.AGENT_ID = da.AGENT_ID
GROUP BY da.AGENT_ID, da.AGENT_NAME, da.CITY;
