create or replace view V_CITY_SEARCH_TO_ORDER(
	CUSTOMER_CITY,
	DT,
	TOTAL_SEARCHES,
	TOTAL_ORDERS,
	SEARCH_TO_ORDER_RATIO
) as
WITH SEARCHES AS (
  SELECT
    CUSTOMER_ID,
    DATE_TRUNC('day', EVENT_TS) AS DT,
    COUNT(*) AS SEARCH_COUNT
  FROM INT.FCT_CUSTOMER_EVENT
  WHERE EVENT_TYPE = 'SEARCH'
  GROUP BY CUSTOMER_ID, DATE_TRUNC('day', EVENT_TS)
),
ORDERS AS (
  SELECT
    CUSTOMER_ID,
    DATE_TRUNC('day', FULL_DATE) AS DT,
    COUNT(*) AS ORDER_COUNT
  FROM MARTS.V_ORDER_ENRICHED
  WHERE IS_DELIVERED = 1
  GROUP BY CUSTOMER_ID, DATE_TRUNC('day', FULL_DATE)
)
SELECT
  c.CITY AS CUSTOMER_CITY,          -- 🔹 FIXED: use c.CITY, not c.CUSTOMER_CITY
  s.DT,
  SUM(s.SEARCH_COUNT) AS TOTAL_SEARCHES,
  SUM(o.ORDER_COUNT)  AS TOTAL_ORDERS,
  CASE WHEN SUM(s.SEARCH_COUNT) > 0
       THEN SUM(o.ORDER_COUNT) / SUM(s.SEARCH_COUNT)
       ELSE NULL
  END AS SEARCH_TO_ORDER_RATIO
FROM SEARCHES s
JOIN ORDERS o
  ON s.CUSTOMER_ID = o.CUSTOMER_ID
 AND s.DT = o.DT
JOIN INT.DIM_CUSTOMER c
  ON s.CUSTOMER_ID = c.CUSTOMER_ID
 AND c.IS_CURRENT = TRUE
GROUP BY c.CITY, s.DT;
