create or replace view V_CUSTOMER_EXPERIENCE_KPI(
	CUSTOMER_ID,
	CUSTOMER_NAME,
	CUSTOMER_CITY,
	CUSTOMER_AREA,
	CUSTOMER_SEGMENT,
	TOTAL_ORDERS,
	DELIVERED_ORDERS,
	CANCELLED_ORDERS,
	AVG_ORDER_VALUE,
	AVG_RATING,
	AVG_SENTIMENT_SCORE,
	LOW_RATING_ORDERS,
	FIRST_ORDER_DATE,
	LAST_ORDER_DATE,
	DAYS_SINCE_LAST_ORDER
) as
SELECT
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_CITY,
  CUSTOMER_AREA,
  CUSTOMER_SEGMENT,

  COUNT(*)                             AS TOTAL_ORDERS,
  SUM(IS_DELIVERED)                    AS DELIVERED_ORDERS,
  SUM(IS_CANCELLED)                    AS CANCELLED_ORDERS,
  AVG(TOTAL_AMOUNT)                    AS AVG_ORDER_VALUE,

  AVG(RATING)                          AS AVG_RATING,
  AVG(SENTIMENT_SCORE)                 AS AVG_SENTIMENT_SCORE,
  SUM(
    CASE 
      WHEN RATING IS NOT NULL AND RATING <= 3 THEN 1 
      ELSE 0 
    END
  )                                    AS LOW_RATING_ORDERS,

  MIN(FULL_DATE)                       AS FIRST_ORDER_DATE,
  MAX(FULL_DATE)                       AS LAST_ORDER_DATE,
  DATEDIFF('day', MAX(FULL_DATE), CURRENT_DATE()) 
                                       AS DAYS_SINCE_LAST_ORDER
FROM MARTS.V_ORDER_ENRICHED
GROUP BY
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_CITY,
  CUSTOMER_AREA,
  CUSTOMER_SEGMENT;
