create or replace view V_ORDER_ENRICHED(
	ORDER_ID,
	ORDER_DATE_KEY,
	FULL_DATE,
	TOTAL_AMOUNT,
	ORDER_SUBTOTAL,
	ORDER_DISCOUNT,
	DELIVERY_FEE,
	NET_FOOD_AMOUNT,
	DISCOUNT_PCT,
	SLA_BREACHED,
	PLATFORM_COMMISSION,
	RESTAURANT_PAYOUT,
	END_TO_END_MIN,
	ORDER_STATUS,
	PAYMENT_METHOD,
	PROMO_ID,
	IS_DELIVERED,
	IS_CANCELLED,
	CUSTOMER_ID,
	CUSTOMER_NAME,
	CUSTOMER_CITY,
	CUSTOMER_AREA,
	CUSTOMER_SEGMENT,
	RESTAURANT_ID,
	RESTAURANT_NAME,
	RESTAURANT_CITY,
	RESTAURANT_AREA,
	CUISINE_PRIMARY,
	COMMISSION_RATE,
	DISTANCE_KM,
	SLA_BREACH_FLAG,
	RATING,
	SENTIMENT_SCORE
) as
SELECT
  fo.ORDER_ID,
  fo.ORDER_DATE_KEY,
  dd.FULL_DATE,
  fo.TOTAL_AMOUNT,
  fo.ORDER_SUBTOTAL,
  fo.ORDER_DISCOUNT,
  fo.DELIVERY_FEE,
  fo.NET_FOOD_AMOUNT,
  fo.DISCOUNT_PCT,
  fo.SLA_BREACHED,
  fo.PLATFORM_COMMISSION,
  fo.RESTAURANT_PAYOUT,
  fo.END_TO_END_MIN,
  fo.ORDER_STATUS,
  fo.PAYMENT_METHOD,
  fo.PROMO_ID,
  fo.IS_DELIVERED,
  fo.IS_CANCELLED,
  c.CUSTOMER_ID,
  c.CUSTOMER_NAME,
  c.CITY         AS CUSTOMER_CITY,
  c.AREA         AS CUSTOMER_AREA,
  c.SEGMENT      AS CUSTOMER_SEGMENT,
  r.RESTAURANT_ID,
  r.RESTAURANT_NAME,
  r.CITY         AS RESTAURANT_CITY,
  r.AREA         AS RESTAURANT_AREA,
  r.CUISINE_PRIMARY,
  r.COMMISSION_RATE,
  dtrip.DISTANCE_KM,
  dtrip.SLA_BREACH_FLAG,
  fb.RATING,
  fb.SENTIMENT_SCORE
FROM INT.FCT_ORDER_ENHANCED fo
LEFT JOIN INT.DIM_DATE dd
  ON fo.ORDER_DATE_KEY = dd.DATE_KEY
LEFT JOIN INT.DIM_CUSTOMER c
  ON fo.CUSTOMER_ID = c.CUSTOMER_ID
 AND c.IS_CURRENT = TRUE
LEFT JOIN INT.DIM_RESTAURANT r
  ON fo.RESTAURANT_ID = r.RESTAURANT_ID
 AND r.IS_CURRENT = TRUE
LEFT JOIN INT.FCT_DELIVERY dtrip
  ON fo.ORDER_ID = dtrip.ORDER_ID
LEFT JOIN INT.FCT_FEEDBACK fb
  ON fo.ORDER_ID = fb.ORDER_ID;
