create or replace view V_RESTAURANT_FEEDBACK_KPI(
	RESTAURANT_ID,
	RESTAURANT_NAME,
	RESTAURANT_CITY,
	CUISINE_PRIMARY,
	TOTAL_ORDERS,
	DELIVERED_ORDERS,
	CANCELLED_ORDERS,
	CANCEL_RATE,
	AVG_CUSTOMER_RATING,
	AVG_SENTIMENT_SCORE,
	LOW_RATING_ORDERS,
	LOW_RATING_DELIVERED_PCT,
	AVG_END_TO_END_MIN,
	AVG_DISTANCE_KM,
	SLA_BREACH_RATE
) as
SELECT
  RESTAURANT_ID,
  RESTAURANT_NAME,
  RESTAURANT_CITY,
  CUISINE_PRIMARY,
  
  COUNT(*)                              AS TOTAL_ORDERS,
  SUM(IS_DELIVERED)                     AS DELIVERED_ORDERS,
  SUM(IS_CANCELLED)                     AS CANCELLED_ORDERS,
  CASE 
    WHEN COUNT(*) > 0 
      THEN SUM(IS_CANCELLED) / COUNT(*)::FLOAT 
    ELSE 0 
  END                                   AS CANCEL_RATE,

  AVG(RATING)                           AS AVG_CUSTOMER_RATING,
  AVG(SENTIMENT_SCORE)                  AS AVG_SENTIMENT_SCORE,
  SUM(
    CASE 
      WHEN RATING IS NOT NULL AND RATING <= 3 THEN 1 
      ELSE 0 
    END
  )                                     AS LOW_RATING_ORDERS,
  CASE 
    WHEN SUM(IS_DELIVERED) > 0 THEN 
      SUM(
        CASE 
          WHEN RATING IS NOT NULL 
           AND RATING <= 3 
           AND IS_DELIVERED = 1 
          THEN 1 ELSE 0 
        END
      ) 
      / SUM(IS_DELIVERED)::FLOAT
    ELSE NULL 
  END                                   AS LOW_RATING_DELIVERED_PCT,

  AVG(END_TO_END_MIN)                   AS AVG_END_TO_END_MIN,
  AVG(DISTANCE_KM)                      AS AVG_DISTANCE_KM,
  AVG(SLA_BREACH_FLAG)                  AS SLA_BREACH_RATE
FROM MARTS.V_ORDER_ENRICHED
GROUP BY
  RESTAURANT_ID,
  RESTAURANT_NAME,
  RESTAURANT_CITY,
  CUISINE_PRIMARY;
