create or replace view V_DAILY_CITY_KPI_DT(
	FULL_DATE,
	CUSTOMER_CITY,
	RESTAURANT_CITY,
	TOTAL_ORDERS,
	GMV,
	DELIVERED_ORDERS,
	CANCELLED_ORDERS,
	AVG_RATING,
	AVG_SENTIMENT_SCORE,
	AVG_SLA_BREACH_RATE
) as
SELECT *
FROM DT_DAILY_CITY_KPI;
