create or replace view V_RESTAURANT_ADVANCED_KPI(
	RESTAURANT_ID,
	RESTAURANT_NAME,
	RESTAURANT_CITY,
	CUISINE_PRIMARY,
	FULL_DATE,
	GMV,
	DELIVERED_ORDERS,
	CANCELLED_ORDERS,
	RESTAURANT_PAYOUT,
	PLATFORM_COMMISSION,
	SLA_BREACH_RATE,
	AVG_RATING,
	AVG_DELIVERY_TIME_MIN,
	GMV_7D,
	GMV_30D,
	GMV_7D_PREV,
	GMV_7D_WOW_GROWTH
) as
WITH DAILY AS (
  SELECT
    RESTAURANT_ID,
    RESTAURANT_NAME,
    RESTAURANT_CITY,
    CUISINE_PRIMARY,                     -- 🔹 add cuisine as a dimension
    FULL_DATE,
    SUM(TOTAL_AMOUNT)           AS GMV,
    SUM(IS_DELIVERED)           AS DELIVERED_ORDERS,
    SUM(IS_CANCELLED)           AS CANCELLED_ORDERS,
    SUM(RESTAURANT_PAYOUT)      AS RESTAURANT_PAYOUT,
    SUM(PLATFORM_COMMISSION)    AS PLATFORM_COMMISSION,
    AVG(SLA_BREACHED)           AS SLA_BREACH_RATE,
    AVG(RATING)                 AS AVG_RATING,
    AVG(END_TO_END_MIN)         AS AVG_DELIVERY_TIME_MIN
  FROM MARTS.V_ORDER_ENRICHED
  GROUP BY
    RESTAURANT_ID,
    RESTAURANT_NAME,
    RESTAURANT_CITY,
    CUISINE_PRIMARY,
    FULL_DATE
),
WINDOWED AS (
  SELECT
    RESTAURANT_ID,
    RESTAURANT_NAME,
    RESTAURANT_CITY,
    CUISINE_PRIMARY,
    FULL_DATE,
    GMV,
    DELIVERED_ORDERS,
    CANCELLED_ORDERS,
    RESTAURANT_PAYOUT,
    PLATFORM_COMMISSION,
    SLA_BREACH_RATE,
    AVG_RATING,
    AVG_DELIVERY_TIME_MIN,
    -- rolling windows
    SUM(GMV)  OVER (
      PARTITION BY RESTAURANT_ID
      ORDER BY FULL_DATE
      ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS GMV_7D,
    SUM(GMV)  OVER (
      PARTITION BY RESTAURANT_ID
      ORDER BY FULL_DATE
      ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS GMV_30D
  FROM DAILY
)
SELECT
  *,
  LAG(GMV_7D, 7) OVER (
    PARTITION BY RESTAURANT_ID
    ORDER BY FULL_DATE
  ) AS GMV_7D_PREV,
  CASE
    WHEN LAG(GMV_7D, 7) OVER (PARTITION BY RESTAURANT_ID ORDER BY FULL_DATE) IS NULL
      OR LAG(GMV_7D, 7) OVER (PARTITION BY RESTAURANT_ID ORDER BY FULL_DATE) = 0
    THEN NULL
    ELSE
      (GMV_7D - LAG(GMV_7D, 7) OVER (PARTITION BY RESTAURANT_ID ORDER BY FULL_DATE))
      / LAG(GMV_7D, 7) OVER (PARTITION BY RESTAURANT_ID ORDER BY FULL_DATE)
  END AS GMV_7D_WOW_GROWTH
FROM WINDOWED;
