create or replace pipe RESTAURANT_PIPE auto_ingest=true integration='AZURE_QUEUE_INT' as COPY INTO RAW.RESTAURANT_RAW
FROM @RAW.ZOMATO_EXT_STAGE/restaurant/
FILE_FORMAT = (FORMAT_NAME = RAW.FF_CSV_STD);
