create or replace task TASK_LOAD_DIMS
	warehouse=WH_ZOMATO
	schedule='USING CRON 0 * * * * Asia/Kolkata'
	as BEGIN
  CALL UTIL.SP_LOAD_DIM_CUSTOMER_SCD2();
  CALL UTIL.SP_LOAD_DIM_RESTAURANT_SCD2();
  CALL UTIL.SP_LOAD_DIM_RESTAURANT_SCD3();
  CALL UTIL.SP_LOAD_DIM_DELIVERY_AGENT();
  CALL UTIL.SP_LOAD_DIM_PROMOTION();
END;
