create or replace TABLE FCT_DELIVERY (
	TRIP_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	AGENT_ID NUMBER(38,0),
	PICKUP_TIME TIMESTAMP_NTZ(9),
	DROP_TIME TIMESTAMP_NTZ(9),
	DISTANCE_KM NUMBER(10,2),
	ESTIMATED_TIME_MIN NUMBER(38,0),
	ACTUAL_TIME_MIN NUMBER(38,0),
	SLA_BREACH_FLAG NUMBER(38,0)
);
