create or replace TABLE FCT_FEEDBACK (
	FEEDBACK_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	RATING NUMBER(38,0),
	COMMENT VARCHAR(16777216),
	SENTIMENT_SCORE FLOAT,
	CREATED_AT TIMESTAMP_NTZ(9)
);
