create or replace view V_DELIVERY_TRIP_STG(
	TRIP_ID,
	ORDER_ID,
	AGENT_ID,
	PICKUP_TIME,
	DROP_TIME,
	DISTANCE_KM,
	ESTIMATED_TIME_MIN,
	ACTUAL_TIME_MIN,
	SLA_BREACH_FLAG
) as
SELECT
  TRY_TO_NUMBER(TRIP_ID)                                      AS TRIP_ID,
  TRY_TO_NUMBER(ORDER_ID)                                     AS ORDER_ID,
  TRY_TO_NUMBER(AGENT_ID)                                     AS AGENT_ID,
  TRY_TO_TIMESTAMP_NTZ(PICKUP_TIME)                           AS PICKUP_TIME,
  TRY_TO_TIMESTAMP_NTZ(DROP_TIME)                             AS DROP_TIME,
  COALESCE(TRY_TO_DOUBLE(DISTANCE_KM), 0.0)                   AS DISTANCE_KM,
  COALESCE(TRY_TO_NUMBER(ESTIMATED_TIME_MIN), 0)              AS ESTIMATED_TIME_MIN,
  COALESCE(TRY_TO_NUMBER(ACTUAL_TIME_MIN), 0)                 AS ACTUAL_TIME_MIN,
  COALESCE(TRY_TO_NUMBER(SLA_BREACH_FLAG), 0)                 AS SLA_BREACH_FLAG
FROM RAW.DELIVERY_TRIP_RAW;
