create or replace view V_ORDER_HEADER_STG(
	ORDER_ID,
	CUSTOMER_ID,
	RESTAURANT_ID,
	ORDER_CREATED_AT,
	ORDER_STATUS,
	PAYMENT_METHOD,
	PROMO_ID,
	ORDER_SUBTOTAL,
	ORDER_DISCOUNT,
	DELIVERY_FEE,
	TOTAL_AMOUNT,
	EXPECTED_DELIVERY_AT,
	ACTUAL_DELIVERY_AT,
	CANCELLATION_REASON
) as
SELECT
  TRY_TO_NUMBER(ORDER_ID)                                     AS ORDER_ID,
  TRY_TO_NUMBER(CUSTOMER_ID)                                  AS CUSTOMER_ID,
  TRY_TO_NUMBER(RESTAURANT_ID)                                AS RESTAURANT_ID,
  TRY_TO_TIMESTAMP_NTZ(ORDER_CREATED_AT)                      AS ORDER_CREATED_AT,
  UPPER(TRIM(ORDER_STATUS))                                   AS ORDER_STATUS,
  UPPER(TRIM(PAYMENT_METHOD))                                 AS PAYMENT_METHOD,
  TRY_TO_NUMBER(PROMO_ID)                                     AS PROMO_ID,
  COALESCE(TRY_TO_NUMBER(ORDER_SUBTOTAL), 0)                  AS ORDER_SUBTOTAL,
  COALESCE(TRY_TO_NUMBER(ORDER_DISCOUNT), 0)                  AS ORDER_DISCOUNT,
  COALESCE(TRY_TO_NUMBER(DELIVERY_FEE), 0)                    AS DELIVERY_FEE,
  COALESCE(TRY_TO_NUMBER(TOTAL_AMOUNT), 0)                    AS TOTAL_AMOUNT,
  TRY_TO_TIMESTAMP_NTZ(EXPECTED_DELIVERY_AT)                  AS EXPECTED_DELIVERY_AT,
  TRY_TO_TIMESTAMP_NTZ(ACTUAL_DELIVERY_AT)                    AS ACTUAL_DELIVERY_AT,
  NULLIF(TRIM(CANCELLATION_REASON), '')                       AS CANCELLATION_REASON
FROM RAW.ORDER_HEADER_RAW;
