create or replace view V_ORDER_ITEM_STG(
	ORDER_ID,
	ORDER_ITEM_ID,
	MENU_ITEM_ID,
	QTY,
	ITEM_PRICE,
	ITEM_DISCOUNT,
	TOTAL_ITEM_AMOUNT
) as
SELECT
  TRY_TO_NUMBER(ORDER_ID)                                     AS ORDER_ID,
  TRY_TO_NUMBER(ORDER_ITEM_ID)                                AS ORDER_ITEM_ID,
  TRY_TO_NUMBER(MENU_ITEM_ID)                                 AS MENU_ITEM_ID,
  COALESCE(TRY_TO_NUMBER(QTY), 0)                             AS QTY,
  COALESCE(TRY_TO_NUMBER(ITEM_PRICE), 0)                      AS ITEM_PRICE,
  COALESCE(TRY_TO_NUMBER(ITEM_DISCOUNT), 0)                   AS ITEM_DISCOUNT,
  COALESCE(TRY_TO_NUMBER(TOTAL_ITEM_AMOUNT), 0)               AS TOTAL_ITEM_AMOUNT
FROM RAW.ORDER_ITEM_RAW;
