create or replace task TASK_LOAD_FACTS
	warehouse=WH_ZOMATO
	schedule='USING CRON 15 * * * * Asia/Kolkata'
	as BEGIN
  CALL UTIL.SP_LOAD_FCT_ORDER_ENHANCED();
  CALL UTIL.SP_LOAD_FCT_DELIVERY();
  CALL UTIL.SP_LOAD_FCT_FEEDBACK();
  CALL UTIL.SP_LOAD_FCT_CUSTOMER_EVENT();
END;
